const poderesFuente =
  (typeof window !== 'undefined' && window.poderes) ||
  (typeof poderes !== 'undefined' ? poderes : {});

const personajes = {
  avispa: {
    name: 'Avispa',
    movimiento: 8,
    ataque: 8,
    defensa: 18,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 0,
    resistenciaAD: 0,
    rango: 3,
    vida: 5,
    agilidad: 20,
    imagen: 'imagenes/avispa.webp',
    poderes: poderesFuente.avispa,
    habilidades: { activas: ['incapacitar'], pasivas: [] },
  },
  hulk: {
    name: 'Hulk',
    movimiento: 9,
    ataque: 11,
    defensa: 17,
    danoCC: 5,
    danoAD: 5,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 1,
    vida: 10,
    agilidad: 10,
    imagen: 'imagenes/hulk.webp',
    poderes: poderesFuente.hulk,
    habilidades: { activas: [], pasivas: ['regeneracion'] },
  },
  capitan: {
    name: 'Capitán América',
    movimiento: 8,
    ataque: 10,
    defensa: 17,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 1,
    resistenciaAD: 2,
    rango: 3,
    vida: 8,
    agilidad: 40,
    imagen: 'imagenes/capitan.webp',
    poderes: poderesFuente.capitan,
    habilidades: { activas: [], pasivas: ['astucia'] },
  },
  spider: {
    name: 'Spider-Man',
    movimiento: 10,
    ataque: 12,
    defensa: 18,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 0,
    resistenciaAD: 0,
    rango: 2,
    vida: 9,
    agilidad: 50,
    imagen: 'imagenes/spider-man.webp',
    poderes: poderesFuente.spider,
    habilidades: { activas: ['incapacitar'], pasivas: ['astucia'] },
  },
  lobezno: {
    name: 'Lobezno',
    movimiento: 8,
    ataque: 10,
    defensa: 16,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 1,
    resistenciaAD: 1,
    rango: 1,
    vida: 8,
    agilidad: 30,
    imagen: 'imagenes/lobezno.webp',
    poderes: poderesFuente.lobezno,
    habilidades: { activas: [], pasivas: ['regeneracion', 'garras'] },
  },
  ciclope: {
    name: 'Cíclope',
    movimiento: 6,
    ataque: 11,
    defensa: 15,
    danoCC: 2,
    danoAD: 4,
    resistenciaCC: 0,
    resistenciaAD: 2,
    rango: 10,
    vida: 5,
    agilidad: 20,
    imagen: 'imagenes/ciclope.webp',
    poderes: poderesFuente.ciclope,
    habilidades: { activas: [], pasivas: [] },
  },
  chaquetaAmarilla: {
    name: 'Chaqueta Amarilla',
    movimiento: 8,
    ataque: 8,
    defensa: 17,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 0,
    resistenciaAD: 0,
    rango: 3,
    vida: 5,
    agilidad: 20,
    imagen: 'imagenes/chaqueta-amarilla.webp',
    poderes: poderesFuente.chaquetaAmarilla,
    habilidades: { activas: ['incapacitar'], pasivas: [] },
  },
  duende: {
    name: 'Duende',
    movimiento: 8,
    ataque: 9,
    defensa: 16,
    danoCC: 2,
    danoAD: 3,
    resistenciaCC: 0,
    resistenciaAD: 0,
    rango: 3,
    vida: 7,
    agilidad: 30,
    imagen: 'imagenes/duende.webp',
    poderes: poderesFuente.duende,
    habilidades: { activas: ['incapacitar'], pasivas: [] },
  },
  dientesDeSable: {
    name: 'Dientes de Sable',
    movimiento: 8,
    ataque: 10,
    defensa: 16,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 1,
    resistenciaAD: 1,
    rango: 0,
    vida: 8,
    agilidad: 30,
    imagen: 'imagenes/dientes-de-sable.webp',
    poderes: poderesFuente.dientesDeSable,
    habilidades: { activas: [], pasivas: ['garras', 'regeneracion'] },
  },
  boomerang: {
    name: 'Boomerang',
    movimiento: 6,
    ataque: 9,
    defensa: 15,
    danoCC: 1,
    danoAD: 2,
    resistenciaCC: 0,
    resistenciaAD: 2,
    rango: 4,
    vida: 5,
    agilidad: 20,
    imagen: 'imagenes/boomerang.webp',
    poderes: poderesFuente.boomerang,
    habilidades: { activas: ['incapacitar', 'explosion'], pasivas: [] },
  },
  juggernaut: {
    name: 'Juggernaut',
    movimiento: 8,
    ataque: 13,
    defensa: 18,
    danoCC: 4,
    danoAD: 4,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 0,
    vida: 10,
    agilidad: 10,
    imagen: 'imagenes/juggernaut.webp',
    poderes: poderesFuente.juggernaut,
    habilidades: { activas: [], pasivas: [] },
  },
  mole: {
    name: 'Mole',
    movimiento: 5,
    ataque: 9,
    defensa: 16,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 1,
    resistenciaAD: 1,
    rango: 0,
    vida: 8,
    agilidad: 10,
    imagen: 'imagenes/mole.webp',
    poderes: poderesFuente.mole,
    habilidades: { activas: ['incapacitar'], pasivas: [] },
  },
  cosa: {
    name: 'La Cosa',
    movimiento: 8,
    ataque: 10,
    defensa: 17,
    danoCC: 4,
    danoAD: 4,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 0,
    vida: 9,
    agilidad: 10,
    imagen: 'imagenes/la-cosa.webp',
    poderes: poderesFuente.cosa,
    habilidades: { activas: [], pasivas: [] },
  },
  antorcha: {
    name: 'Antorcha Humana',
    movimiento: 10,
    ataque: 10,
    defensa: 15,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 0,
    resistenciaAD: 2,
    rango: 5,
    vida: 7,
    agilidad: 20,
    imagen: 'imagenes/antorcha-humana.webp',
    poderes: poderesFuente.antorcha,
    habilidades: { activas: ['explosion', 'pulso'], pasivas: [] },
  },
  doom: {
    name: 'Dr Doom',
    movimiento: 8,
    ataque: 12,
    defensa: 18,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 5,
    vida: 9,
    agilidad: 20,
    imagen: 'imagenes/doom.webp',
    poderes: poderesFuente.doom,
    habilidades: { activas: ['explosion', 'incapacitar'], pasivas: ['astucia'] },
  },
  ultron: {
    name: 'Ultrón',
    movimiento: 12,
    ataque: 14,
    defensa: 18,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 5,
    vida: 10,
    agilidad: 30,
    imagen: 'imagenes/ultron.webp',
    poderes: poderesFuente.ultron,
    habilidades: { activas: ['explosion'], pasivas: [] },
  },
  thor: {
    name: 'Thor',
    movimiento: 8,
    ataque: 12,
    defensa: 17,
    danoCC: 4,
    danoAD: 4,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 5,
    vida: 10,
    agilidad: 20,
    imagen: 'imagenes/thor.webp',
    poderes: poderesFuente.thor,
    habilidades: { activas: [], pasivas: [] },
  },
  iron-man: {
    name: 'Iron Man',
    movimiento: 12,
    ataque: 10,
    defensa: 17,
    danoCC: 3,
    danoAD: 4,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 5,
    vida: 9,
    agilidad: 30,
    imagen: 'imagenes/iron-man.webp',
    poderes: poderesFuente.iron-man,
    habilidades: { activas: ['explosion'], pasivas: ['astucia', 'regeneración'] },
  },
  hulka: {
    name: 'Hulka',
    movimiento: 10,
    ataque: 11,
    defensa: 17,
    danoCC: 4,
    danoAD: 4,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 0,
    vida: 9,
    agilidad: 30,
    imagen: 'imagenes/hulka.webp',
    poderes: poderesFuente.hulka,
    habilidades: { activas: [], pasivas: [] },
  },
  bruja-escarlata: {
    name: 'Bruja Escarlata',
    movimiento: 6,
    ataque: 8,
    defensa: 16,
    danoCC: 1,
    danoAD: 1,
    resistenciaCC: 0,
    resistenciaAD: 0,
    rango: 4,
    vida: 5,
    agilidad: 30,
    imagen: 'imagenes/bruja-escarlata.webp',
    poderes: poderesFuente.bruja-escarlata,
    habilidades: { activas: ['incapacitar', 'probabilidad'], pasivas: [] },
  },
  thanos: {
    name: 'Thanos',
    movimiento: 12,
    ataque: 135,
    defensa: 18,
    danoCC: 4,
    danoAD: 4,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 5,
    vida: 11,
    agilidad: 30,
    imagen: 'imagenes/thanos.webp',
    poderes: poderesFuente.thanos,
    habilidades: { activas: [], pasivas: ['regeneracion'] },
  },
  magneto: {
    name: 'Magneto',
    movimiento: 9,
    ataque: 10,
    defensa: 17,
    danoCC: 4,
    danoAD: 4,
    resistenciaCC: 0,
    resistenciaAD: 2,
    rango: 4,
    vida: 8,
    agilidad: 20,
    imagen: 'imagenes/magneto.webp',
    poderes: poderesFuente.magneto,
    habilidades: { activas: [], pasivas: [] },
  },
  kang: {
    name: 'Kang',
    movimiento: 10,
    ataque: 13,
    defensa: 18,
    danoCC: 2,
    danoAD: 3,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 5,
    vida: 9,
    agilidad: 30,
    imagen: 'imagenes/kang.webp',
    poderes: poderesFuente.kang,
    habilidades: { activas: ['pulso', 'incapacitar'], pasivas: ['fase'] },
  },
  super-skrull: {
    name: 'Súper Skrull',
    movimiento: 8,
    ataque: 11,
    defensa: 16,
    danoCC: 4,
    danoAD: 4,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 4,
    vida: 9,
    agilidad: 30,
    imagen: 'imagenes/super-skrull.webp',
    poderes: poderesFuente.super-skrull,
    habilidades: { activas: ['incapacitar'], pasivas: [] },
  },
};

if (typeof window !== 'undefined') {
  window.personajes = personajes;
}
