const poderesFuente =
  (typeof window !== 'undefined' && window.poderes) ||
  (typeof poderes !== 'undefined' ? poderes : {});

const personajes = {
  agenteShield: {
    nombre: 'Agente SHIELD',
    movimiento: 3,
    ataque: 7,
    defensa: 15,
    dano: 2,
    rango: 3,
    vida: 4,
    agilidad: 0,
    imagen: 'imagenes/agenteShield.webp',
    animacion: 'animaciones/agenteShield.webp',
    poderes: poderesFuente.agenteShield,
    habilidades: { activas: [], pasivas: [] }
  },
  medicoShield: {
    nombre: 'Médico SHIELD',
    movimiento: 3,
    ataque: 6,
    defensa: 14,
    dano: 1,
    rango: 2,
    vida: 4,
    agilidad: 0,
    imagen: 'imagenes/medicoShield.webp',
    animacion: 'animaciones/medicoShield.webp',
    poderes: poderesFuente.medicoShield,
    habilidades: { activas: ['Curar'], pasivas: [] }
  },
  agenteHydra: {
    nombre: 'Agente HYDRA',
    movimiento: 3,
    ataque: 7,
    defensa: 14,
    dano: 2,
    rango: 3,
    vida: 4,
    agilidad: 0,
    imagen: 'imagenes/agenteHydra.webp',
    animacion: 'animaciones/agenteHydra.webp',
    poderes: poderesFuente.agenteHydra,
    habilidades: { activas: [], pasivas: [] }
  },
  medicoHydra: {
    nombre: 'Médico HYDRA',
    movimiento: 3,
    ataque: 7,
    defensa: 14,
    dano: 1,
    rango: 2,
    vida: 4,
    agilidad: 0,
    imagen: 'imagenes/medicoHydra.webp',
    animacion: 'animaciones/medicoHydra.webp',
    poderes: poderesFuente.medicoHydra,
    habilidades: { activas: ['Curar'], pasivas: [] }
  },
  maton: {
    nombre: 'Matón',
    movimiento: 3,
    ataque: 7,
    defensa: 14,
    dano: 2,
    rango: 1,
    vida: 4,
    agilidad: 0,
    imagen: 'imagenes/maton.webp',
    animacion: 'animaciones/maton.webp',
    poderes: poderesFuente.maton,
    habilidades: { activas: [], pasivas: [] }
  },
  esbirro: {
    nombre: 'Esbirro',
    movimiento: 3,
    ataque: 7,
    defensa: 13,
    dano: 2,
    rango: 2,
    vida: 5,
    agilidad: 0,
    imagen: 'imagenes/esbirro.webp',
    animacion: 'animaciones/esbirro.webp',
    poderes: poderesFuente.esbirro,
    habilidades: { activas: [], pasivas: [] }
  },
  agenteSkrull: {
    nombre: 'Agente Skrull',
    movimiento: 4,
    ataque: 7,
    defensa: 15,
    dano: 2,
    rango: 3,
    vida: 4,
    agilidad: 0,
    imagen: 'imagenes/agenteSkrull.webp',
    animacion: 'animaciones/agenteSkrull.webp',
    poderes: poderesFuente.agenteSkrull,
    habilidades: { activas: [], pasivas: [] }
  },
  guerreroSkrull: {
    nombre: 'Guerrero Skrull',
    movimiento: 4,
    ataque: 8,
    defensa: 16,
    dano: 2,
    rango: 4,
    vida: 4,
    agilidad: 0,
    imagen: 'imagenes/guerreroSkrull.webp',
    animacion: 'animaciones/guerreroSkrull.webp',
    poderes: poderesFuente.guerreroSkrull,
    habilidades: { activas: [], pasivas: [] }
  },
  blade: {
    nombre: 'Blade',
    movimiento: 4,
    ataque: 9,
    defensa: 15,
    dano: 2,
    rango: 1,
    vida: 6,
    agilidad: 30,
    imagen: 'imagenes/blade.webp',
    animacion: 'animaciones/blade.webp',
    poderes: poderesFuente.blade,
    habilidades: { activas: [], pasivas: ['Sigilo', 'Cuchillas/Garras/Colmillos', 'Dureza'] }
  },
  lobaVenenosa: {
    nombre: 'Loba Venenosa',
    movimiento: 5,
    ataque: 10,
    defensa: 15,
    dano: 2,
    rango: 1,
    vida: 7,
    agilidad: 10,
    imagen: 'imagenes/lobaVenenosa.webp',
    animacion: 'animaciones/lobaVenenosa.webp',
    poderes: poderesFuente.lobaVenenosa,
    habilidades: { activas: [], pasivas: ['Cuchillas/Garras/Colmillos'] }
  },
  elektra: {
    nombre: 'Elektra',
    movimiento: 4,
    ataque: 9,
    defensa: 16,
    dano: 2,
    rango: 2,
    vida: 6,
    agilidad: 30,
    imagen: 'imagenes/elektra.webp',
    animacion: 'animaciones/elektra.webp',
    poderes: poderesFuente.elektra,
    habilidades: { activas: [], pasivas: ['Sigilo', 'Cuchillas/Garras/Colmillos'] }
  },
  avispa: {
    nombre: 'Avispa',
    movimiento: 4,
    ataque: 8,
    defensa: 19,
    dano: 2,
    rango: 3,
    vida: 5,
    agilidad: 20,
    imagen: 'imagenes/avispa.webp',
    animacion: 'animaciones/avispa.webp',
    poderes: poderesFuente.avispa,
    habilidades: { activas: ['Incapacitar', 'Mejora de Agilidad'], pasivas: ['Volar'] }
  },
  constrictor: {
    nombre: 'Constrictor',
    movimiento: 3,
    ataque: 10,
    defensa: 16,
    dano: 2,
    rango: 2,
    vida: 6,
    agilidad: 10,
    imagen: 'imagenes/constrictor.webp',
    animacion: 'animaciones/constrictor.webp',
    poderes: poderesFuente.constrictor,
    habilidades: { activas: ['Incapacitar','Mejora de Defensa'], pasivas: [] }
  },
  boomerang: {
    nombre: 'Boomerang',
    movimiento: 3,
    ataque: 9,
    defensa: 15,
    dano: 1,
    rango: 4,
    vida: 5,
    agilidad: 30,
    imagen: 'imagenes/boomerang.webp',
    animacion: 'animaciones/boomerang.webp',
    poderes: poderesFuente.boomerang,
    habilidades: { activas: ['Incapacitar','Explosión', 'Experto a/d', 'Defensa a/d'], pasivas: [] }
  },
  kingpin: {
    nombre: 'Kingpin',
    movimiento: 3,
    ataque: 8,
    defensa: 16,
    dano: 2,
    rango: 1,
    vida: 7,
    agilidad: 10,
    imagen: 'imagenes/kingpin.webp',
    animacion: 'animaciones/kingpin.webp',
    poderes: poderesFuente.kingpin,
    habilidades: { activas: ['Mejora de Agilidad'], pasivas: ['Dureza'] }
  },
  buitre: {
    nombre: 'Buitre',
    movimiento: 5,
    ataque: 8,
    defensa: 16,
    dano: 2,
    rango: 1,
    vida: 5,
    agilidad: 30,
    imagen: 'imagenes/buitre.webp',
    animacion: 'animaciones/buitre.webp',
    poderes: poderesFuente.buitre,
    habilidades: { activas: [], pasivas: ['Volar'] }
  },
  jeanGrey: {
    nombre: 'Jean Grey',
    movimiento: 3,
    ataque: 7,
    defensa: 16,
    dano: 1,
    rango: 1,
    vida: 6,
    agilidad: 10,
    imagen: 'imagenes/jeanGrey.webp',
    animacion: 'animaciones/jeanGrey.webp',
    poderes: poderesFuente.jeanGrey,
    habilidades: { activas: ['Telekinesis', 'Curar'], pasivas: ['Defensa a/d'] }
  },
  duende: {
    nombre: 'Duende',
    movimiento: 4,
    ataque: 9,
    defensa: 16,
    dano: 2,
    rango: 3,
    vida: 7,
    agilidad: 30,
    imagen: 'imagenes/duende.webp',
    animacion: 'animaciones/duende.webp',
    poderes: poderesFuente.duende,
    habilidades: { activas: ['Incapacitar'], pasivas: ['Experto a/d', 'Volar'] }
  },
  dientesDeSable: {
    nombre: 'Dientes de Sable',
    movimiento: 4,
    ataque: 10,
    defensa: 16,
    dano: 3,
    rango: 1,
    vida: 8,
    agilidad: 30,
    imagen: 'imagenes/dientesDeSable.webp',
    animacion: 'animaciones/dientesDeSable.webp',
    poderes: poderesFuente.dientesDeSable,
    habilidades: { activas: [], pasivas: ['Sigilo', 'Cuchillas/Garras/Colmillos', 'Dureza','Regeneración'] }
  },
  hulk: {
    nombre: 'Hulk',
    movimiento: 5,
    ataque: 12,
    defensa: 17,
    dano: 5,
    rango: 1,
    vida: 10,
    agilidad: 10,
    imagen: 'imagenes/hulk.webp',
    animacion: 'animaciones/hulk.webp',
    poderes: poderesFuente.hulk,
    habilidades: { activas: [''], pasivas: ['Saltar/Trepar', 'Superfuerza', 'Invulnerabilidad','Regeneración'] }
  },
  maestroMarionetas: {
    nombre: 'Maestro Marionetas',
    movimiento: 3,
    ataque: 7,
    defensa: 15,
    dano: 1,
    rango: 2,
    vida: 5,
    agilidad: 10,
    imagen: 'imagenes/maestroMarionetas.webp',
    animacion: 'animaciones/maestroMarionetas.webp',
    poderes: poderesFuente.maestroMarionetas,
    habilidades: { activas: ['Control Mental'], pasivas: [] }
  },
  annihilus: {
    nombre: 'Annihilus',
    movimiento: 4,
    ataque: 11,
    defensa: 16,
    dano: 3,
    rango: 5,
    vida: 9,
    agilidad: 40,
    imagen: 'imagenes/annihilus.webp',
    animacion: 'animaciones/annihilus.webp',
    poderes: poderesFuente.annihilus,
    habilidades: { activas: [], pasivas: ['Invulnerable','Volar'] }
  },
  capitanAmerica: {
    nombre: 'Capitán América',
    movimiento: 4,
    ataque: 10,
    defensa: 17,
    dano: 2,
    rango: 3,
    vida: 8,
    agilidad: 40,
    imagen: 'imagenes/capitanAmerica.webp',
    animacion: 'animaciones/capitanAmerica.webp',
    poderes: poderesFuente.capitanAmerica,
    habilidades: { activas: ['Mejora de Agilidad','Curar'], pasivas: ['Defensa a/d','Astucia','Dureza'] }
  },
  spiderMan: {
    nombre: 'Spider-Man',
    movimiento: 5,
    ataque: 12,
    defensa: 18,
    dano: 2,
    rango: 4,
    vida: 9,
    agilidad: 50,
    imagen: 'imagenes/spiderMan.webp',
    animacion: 'animaciones/spiderMan.webp',
    poderes: poderesFuente.spiderMan,
    habilidades: { activas: ['Incapacitar'], pasivas: ['Saltar/Trepar','Astucia','Doble ataque c/c','Mejora de Defensa'] }
  },
  lobezno: {
    nombre: 'Lobezno',
    movimiento: 4,
    ataque: 12,
    defensa: 16,
    dano: 2,
    rango: 1,
    vida: 8,
    agilidad: 30,
    imagen: 'imagenes/lobezno.webp',
    animacion: 'animaciones/lobezno.webp',
    poderes: poderesFuente.lobezno,
    habilidades: { activas: [], pasivas: ['Sigilo','Cuchillas/Garras/Colmillos','Dureza','Regeneración' ] }
  },
  profesorXavier: {
    nombre: 'Profesor Xavier',
    movimiento: 3,
    ataque: 11,
    defensa: 16,
    dano: 1,
    rango: 5,
    vida: 7,
    agilidad: 10,
    imagen: 'imagenes/profesorXavier.webp',
    animacion: 'animaciones/profesorXavier.webp',
    poderes: poderesFuente.profesorXavier,
    habilidades: { activas: ['Control Mental','Mejora de Defensa','Mejora de Agilidad'], pasivas: [] }
  },
  juggernaut: {
    nombre: 'Juggernaut',
    movimiento: 4,
    ataque: 13,
    defensa: 18,
    dano: 4,
    rango: 1,
    vida: 10,
    agilidad: 0,
    imagen: 'imagenes/juggernaut.webp',
    animacion: 'animaciones/juggernaut.webp',
    poderes: poderesFuente.juggernaut,
    habilidades: { activas: [], pasivas: ['Superfuerza','Invulnerable'] }
  },
  ciclope: {
    nombre: 'Cíclope',
    movimiento: 3,
    ataque: 11,
    defensa: 15,
    dano: 2,
    rango: 5,
    vida: 6,
    agilidad: 20,
    imagen: 'imagenes/ciclope.webp',
    animacion: 'animaciones/ciclope.webp',
    poderes: poderesFuente.ciclope,
    habilidades: { activas: [], pasivas: ['Experto a/d','Defensa a/d'] }
  },
  panteraNegra: {
    nombre: 'Pantera Negra',
    movimiento: 5,
    ataque: 9,
    defensa: 16,
    dano: 2,
    rango: 2,
    vida: 6,
    agilidad: 40,
    imagen: 'imagenes/panteraNegra.webp',
    animacion: 'animaciones/panteraNegra.webp',
    poderes: poderesFuente.panteraNegra,
    habilidades: { activas: [], pasivas: ['Saltar/Trepar','Astucia','Cuchillas/Garras/Colmillos'] }
  },
  ventisca: {
    nombre: 'Ventisca',
    movimiento: 4,
    ataque: 11,
    defensa: 16,
    dano: 1,
    rango: 4,
    vida: 6,
    agilidad: 10,
    imagen: 'imagenes/ventisca.webp',
    animacion: 'animaciones/ventisca.webp',
    poderes: poderesFuente.ventisca,
    habilidades: { activas: ['Pulso','Barrera'], pasivas: [] }
  },
  pyro: {
    nombre: 'Pyro',
    movimiento: 4,
    ataque: 9,
    defensa: 17,
    dano: 1,
    rango: 4,
    vida: 6,
    agilidad: 10,
    imagen: 'imagenes/pyro.webp',
    animacion: 'animaciones/pyro.webp',
    poderes: poderesFuente.pyro,
    habilidades: { activas: ['Incapacitar','Explosión'], pasivas: ['Experto a/d'] }
  },
  torbellino: {
    nombre: 'Torbellino',
    movimiento: 6,
    ataque: 8,
    defensa: 16,
    dano: 3,
    rango: 1,
    vida: 6,
    agilidad: 40,
    imagen: 'imagenes/torbellino.webp',
    animacion: 'animaciones/torbellino.webp',
    poderes: poderesFuente.torbellino,
    habilidades: { activas: [], pasivas: ['Doble ataque c/c','Defensa a/d'] }
  },
  daredevil: {
    nombre: 'Daredevil',
    movimiento: 4,
    ataque: 9,
    defensa: 17,
    dano: 2,
    rango: 2,
    vida: 6,
    agilidad: 40,
    imagen: 'imagenes/daredevil.webp',
    animacion: 'animaciones/daredevil.webp',
    poderes: poderesFuente.daredevil,
    habilidades: { activas: ['Incapacitar'], pasivas: [] }
  },
  bullseye: {
    nombre: 'Bullseye',
    movimiento: 3,
    ataque: 11,
    defensa: 16,
    dano: 1,
    rango: 5,
    vida: 6,
    agilidad: 50,
    imagen: 'imagenes/bullseye.webp',
    animacion: 'animaciones/bullseye.webp',
    poderes: poderesFuente.bullseye,
    habilidades: { activas: [], pasivas: ['Experto a/d','Defensa a/d'] }
  },
  brujaEscarlata: {
    nombre: 'Bruja Escarlata',
    movimiento: 3,
    ataque: 8,
    defensa: 16,
    dano: 1,
    rango: 4,
    vida: 5,
    agilidad: 10,
    imagen: 'imagenes/brujaEscarlata.webp',
    animacion: 'animaciones/brujaEscarlata.webp',
    poderes: poderesFuente.brujaEscarlata,
    habilidades: { activas: ['Incapacitar','Mejora de Crítico'], pasivas: ['Astucia'] }
  },
  mercurio: {
    nombre: 'Mercurio',
    movimiento: 7,
    ataque: 9,
    defensa: 16,
    dano: 2,
    rango: 1,
    vida: 6,
    agilidad: 70,
    imagen: 'imagenes/mercurio.webp',
    animacion: 'animaciones/mercurio.webp',
    poderes: poderesFuente.mercurio,
    habilidades: { activas: [], pasivas: ['Defensa a/d','Doble ataque c/c'] }
  },
  mrHyde: {
    nombre: 'Mr Hyde',
    movimiento: 4,
    ataque: 11,
    defensa: 15,
    dano: 3,
    rango: 1,
    vida: 7,
    agilidad: 10,
    imagen: 'imagenes/mrHyde.webp',
    animacion: 'animaciones/mrHyde.webp',
    poderes: poderesFuente.mrHyde,
    habilidades: { activas: [], pasivas: ['Superfuerza','Dureza'] }
  },
  klaw: {
    nombre: 'Klaw',
    movimiento: 4,
    ataque: 11,
    defensa: 16,
    dano: 2,
    rango: 5,
    vida: 8,
    agilidad: 20,
    imagen: 'imagenes/klaw.webp',
    animacion: 'animaciones/klaw.webp',
    poderes: poderesFuente.klaw,
    habilidades: { activas: ['Incapacitar'], pasivas: ['Barrera','Experto a/d'] }
  },
  controller: {
    nombre: 'Controller',
    movimiento: 3,
    ataque: 12,
    defensa: 17,
    dano: 3,
    rango: 1,
    vida: 7,
    agilidad: 30,
    imagen: 'imagenes/controller.webp',
    animacion: 'animaciones/controller.webp',
    poderes: poderesFuente.controller,
    habilidades: { activas: ['Control Mental'], pasivas: ['Superfuerza','Dureza','Regeneración'] }
  },
  hercules: {
    nombre: 'Hércules',
    movimiento: 4,
    ataque: 11,
    defensa: 15,
    dano: 4,
    rango: 1,
    vida: 9,
    agilidad: 20,
    imagen: 'imagenes/hercules.webp',
    animacion: 'animaciones/hercules.webp',
    poderes: poderesFuente.hercules,
    habilidades: { activas: [], pasivas: ['Superfuerza','Dureza'] }
  },
  picara: {
    nombre: 'Pícara',
    movimiento: 5,
    ataque: 10,
    defensa: 15,
    dano: 3,
    rango: 1,
    vida: 8,
    agilidad: 20,
    imagen: 'imagenes/picara.webp',
    animacion: 'animaciones/picara.webp',
    poderes: poderesFuente.picara,
    habilidades: { activas: [], pasivas: ['Robo de Vida','Invulnerable','Volar'] }
  },
  drExtrano: {
    nombre: 'Dr Extraño',
    movimiento: 3,
    ataque: 11,
    defensa: 17,
    dano: 2,
    rango: 5,
    vida: 8,
    agilidad: 20,
    imagen: 'imagenes/drExtrano.webp',
    animacion: 'animaciones/drExtrano.webp',
    poderes: poderesFuente.drExtrano,
    habilidades: { activas: ['Incapacitar','Telekinesis','Pulso','Barrera','Curar','Mejora de Crítico','Mejora de Ataque'], pasivas: ['Volar','Fase','Defensa a/d','Experto a/d'] }
  },
  magneto: {
    nombre: 'Magneto',
    movimiento: 5,
    ataque: 10,
    defensa: 17,
    dano: 4,
    rango: 4,
    vida: 8,
    agilidad: 30,
    imagen: 'imagenes/magneto.webp',
    animacion: 'animaciones/magneto.webp',
    poderes: poderesFuente.magneto,
    habilidades: { activas: ['Telekinesis','Mejora de Agilidad'], pasivas: ['Defensa a/d','Volar'] }
  },
  kang: {
    nombre: 'Kang',
    movimiento: 5,
    ataque: 13,
    defensa: 18,
    dano: 2,
    rango: 5,
    vida: 9,
    agilidad: 10,
    imagen: 'imagenes/kang.webp',
    animacion: 'animaciones/kang.webp',
    poderes: poderesFuente.kang,
    habilidades: { activas: ['Incapacitar','Pulso'], pasivas: ['Invulnerable','Experto a/d','Fase'] }
  },
  ultron: {
    nombre: 'Ultrón',
    movimiento: 6,
    ataque: 14,
    defensa: 18,
    dano: 3,
    rango: 5,
    vida: 10,
    agilidad: 30,
    imagen: 'imagenes/ultron.webp',
    animacion: 'animaciones/ultron.webp',
    poderes: poderesFuente.ultron,
    habilidades: { activas: ['Explosión'], pasivas: ['Invulnerable','Volar'] }
  },
  firelord: {
    nombre: 'Firelord',
    movimiento: 6,
    ataque: 13,
    defensa: 18,
    dano: 3,
    rango: 4,
    vida: 10,
    agilidad: 60,
    imagen: 'imagenes/firelord.webp',
    animacion: 'animaciones/firelord.webp',
    poderes: poderesFuente.firelord,
    habilidades: { activas: ['Explosión','Pulso','Barrera'], pasivas: ['Defensa a/d','Experto a/d','Volar'] }
  },
  vision: {
    nombre: 'Vision',
    movimiento: 5,
    ataque: 11,
    defensa: 17,
    dano: 3,
    rango: 5,
    vida: 10,
    agilidad: 20,
    imagen: 'imagenes/vision.webp',
    animacion: 'animaciones/vision.webp',
    poderes: poderesFuente.vision,
    habilidades: { activas: [], pasivas: ['Volar','Superfuerza','Invulnerable'] }
  },
  quasar: {
    nombre: 'Quasar',
    movimiento: 5,
    ataque: 11,
    defensa: 18,
    dano: 1,
    rango: 5,
    vida: 8,
    agilidad: 20,
    imagen: 'imagenes/quasar.webp',
    animacion: 'animaciones/quasar.webp',
    poderes: poderesFuente.quasar,
    habilidades: { activas: ['Incapacitar','Telekinesis','Barrera','Mejora de Defensa'], pasivas: ['Experto a/d','Volar'] }
  },
  thanos: {
    nombre: 'Thanos',
    movimiento: 6,
    ataque: 15,
    defensa: 18,
    dano: 4,
    rango: 5,
    vida: 11,
    agilidad: 30,
    imagen: 'imagenes/thanos.webp',
    animacion: 'animaciones/thanos.webp',
    poderes: poderesFuente.thanos,
    habilidades: { activas: [], pasivas: ['Invulnerable','Regeneración','Volar'] }
  },
  pesadilla: {
    nombre: 'Pesadilla',
    movimiento: 5,
    ataque: 14,
    defensa: 18,
    dano: 3,
    rango: 1,
    vida: 10,
    agilidad: 80,
    imagen: 'imagenes/pesadilla.webp',
    animacion: 'animaciones/pesadilla.webp',
    poderes: poderesFuente.pesadilla,
    habilidades: { activas: ['Incapacitar','Mejora de Ataque'], pasivas: ['Robo de Vida','Invulnerable'] }
  },
  centinela: {
    nombre: 'Centinela',
    movimiento: 6,
    ataque: 11,
    defensa: 17,
    dano: 4,
    rango: 5,
    vida: 18,
    agilidad: 20,
    imagen: 'imagenes/centinela.webp',
    animacion: 'animaciones/centinela.webp',
    poderes: poderesFuente.centinela,
    habilidades: { activas: ['Incapacitar','Explosión'], pasivas: ['Dureza','Defensa a/d','Volar'] }
  }
};

if (typeof window !== 'undefined') {
  window.personajes = personajes;
}