const personajes = {
  avispa: {
    name: 'Avispa',
    movimiento: 8,
    ataque: 8,
    defensa: 18,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 0,
    resistenciaAD: 0,
    rango: 3,
    vida: 5,
    agilidad: 20,
    imagen: 'imagenes/avispa.webp',
    poderes: poderes.avispa,
    habilidades: { activas: ['incapacitar'], pasivas: [] },
  },
  hulk: {
    name: 'Hulk',
    movimiento: 9,
    ataque: 11,
    defensa: 17,
    danoCC: 5,
    danoAD: 5,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 1,
    vida: 10,
    agilidad: 10,
    imagen: 'imagenes/hulk.webp',
    poderes: poderes.hulk,
    habilidades: { activas: [], pasivas: ['regeneracion'] },
  },
  capitan: {
    name: 'Capitán América',
    movimiento: 8,
    ataque: 10,
    defensa: 17,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 1,
    resistenciaAD: 2,
    rango: 3,
    vida: 8,
    agilidad: 40,
    imagen: 'imagenes/capitan.webp',
    poderes: poderes.capitan,
    habilidades: { activas: [], pasivas: ['astucia'] },
  },
  spider: {
    name: 'Spider-Man',
    movimiento: 10,
    ataque: 12,
    defensa: 18,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 0,
    resistenciaAD: 0,
    rango: 2,
    vida: 9,
    agilidad: 50,
    imagen: 'imagenes/spider-man.webp',
    poderes: poderes.spider,
    habilidades: { activas: ['incapacitar'], pasivas: ['astucia'] },
  },
  lobezno: {
    name: 'Lobezno',
    movimiento: 8,
    ataque: 10,
    defensa: 16,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 1,
    resistenciaAD: 1,
    rango: 1,
    vida: 8,
    agilidad: 30,
    imagen: 'imagenes/lobezno.webp',
    poderes: poderes.lobezno,
    habilidades: { activas: [], pasivas: ['regeneracion', 'garras'] },
  },
  ciclope: {
    name: 'Cíclope',
    movimiento: 6,
    ataque: 11,
    defensa: 15,
    danoCC: 2,
    danoAD: 4,
    resistenciaCC: 0,
    resistenciaAD: 2,
    rango: 10,
    vida: 5,
    agilidad: 20,
    imagen: 'imagenes/ciclope.webp',
    poderes: poderes.ciclope,
    habilidades: { activas: [], pasivas: [] },
  },
  chaquetaAmarilla: {
    name: 'Chaqueta Amarilla',
    movimiento: 8,
    ataque: 8,
    defensa: 17,
    danoCC: 2,
    danoAD: 2,
    resistenciaCC: 0,
    resistenciaAD: 0,
    rango: 3,
    vida: 5,
    agilidad: 20,
    imagen: 'imagenes/chaqueta-amarilla.webp',
    poderes: poderes.chaquetaAmarilla,
    habilidades: { activas: ['incapacitar'], pasivas: [] },
  },
  duende: {
    name: 'Duende',
    movimiento: 8,
    ataque: 9,
    defensa: 16,
    danoCC: 2,
    danoAD: 3,
    resistenciaCC: 0,
    resistenciaAD: 0,
    rango: 3,
    vida: 7,
    agilidad: 30,
    imagen: 'imagenes/duende.webp',
    poderes: poderes.duende,
    habilidades: { activas: ['incapacitar'], pasivas: [] },
  },
  dientesDeSable: {
    name: 'Dientes de Sable',
    movimiento: 8,
    ataque: 10,
    defensa: 16,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 1,
    resistenciaAD: 1,
    rango: 0,
    vida: 8,
    agilidad: 30,
    imagen: 'imagenes/dientes-de-sable.webp',
    poderes: poderes.dientesDeSable,
    habilidades: { activas: [], pasivas: ['garras', 'regeneracion'] },
  },
  boomerang: {
    name: 'Boomerang',
    movimiento: 6,
    ataque: 9,
    defensa: 15,
    danoCC: 1,
    danoAD: 2,
    resistenciaCC: 0,
    resistenciaAD: 2,
    rango: 4,
    vida: 5,
    agilidad: 20,
    imagen: 'imagenes/boomerang.webp',
    poderes: poderes.boomerang,
    habilidades: { activas: ['incapacitar', 'explosion'], pasivas: [] },
  },
  juggernaut: {
    name: 'Juggernaut',
    movimiento: 8,
    ataque: 13,
    defensa: 18,
    danoCC: 4,
    danoAD: 4,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 0,
    vida: 10,
    agilidad: 10,
    imagen: 'imagenes/juggernaut.webp',
    poderes: poderes.juggernaut,
    habilidades: { activas: [], pasivas: [] },
  },
  mole: {
    name: 'Mole',
    movimiento: 5,
    ataque: 9,
    defensa: 16,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 1,
    resistenciaAD: 1,
    rango: 0,
    vida: 8,
    agilidad: 10,
    imagen: 'imagenes/mole.webp',
    poderes: poderes.mole,
    habilidades: { activas: ['incapacitar'], pasivas: [] },
  },
  cosa: {
    name: 'La Cosa',
    movimiento: 8,
    ataque: 10,
    defensa: 17,
    danoCC: 4,
    danoAD: 4,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 0,
    vida: 9,
    agilidad: 10,
    imagen: 'imagenes/la-cosa.webp',
    poderes: poderes.cosa,
    habilidades: { activas: [], pasivas: [] },
  },
  antorcha: {
    name: 'Antorcha Humana',
    movimiento: 10,
    ataque: 10,
    defensa: 15,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 0,
    resistenciaAD: 2,
    rango: 5,
    vida: 7,
    agilidad: 20,
    imagen: 'imagenes/antorcha-humana.webp',
    poderes: poderes.antorcha,
    habilidades: { activas: ['explosion', 'pulso'], pasivas: [] },
  },
  doom: {
    name: 'Dr Doom',
    movimiento: 8,
    ataque: 12,
    defensa: 18,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 5,
    vida: 9,
    agilidad: 20,
    imagen: 'imagenes/doom.webp',
    poderes: poderes.doom,
    habilidades: { activas: ['explosion', 'incapacitar'], pasivas: ['astucia'] },
  },
  ultron: {
    name: 'Ultrón',
    movimiento: 12,
    ataque: 14,
    defensa: 18,
    danoCC: 3,
    danoAD: 3,
    resistenciaCC: 2,
    resistenciaAD: 2,
    rango: 5,
    vida: 10,
    agilidad: 30,
    imagen: 'imagenes/ultron.webp',
    poderes: poderes.ultron,
    habilidades: { activas: ['explosion'], pasivas: [] },
  },
};
